if("object"==typeof JSF)JSF.sso="//vj0.6rooms.com/csjs/_/sso_22.js";var isIpad=/ipad/i.test(navigator.userAgent),isIphone=/iPhone/i.test(navigator.userAgent);
if(isIpad||isIphone){var _html=isIpad?'iPad\u7528\u6237\u8bf7<a href="http://v.6.cn/ipad_app.php">\u5b89\u88c5app</a>':'iPhone\u7528\u6237\u8bf7<a href="https://itunes.apple.com/cn/app/xiu-chang/id546300644?l=cn&mt=8">\u5b89\u88c5app</a>',_div=document.createElement("div");_div.className="for_ipad_install";_div.style.zIndex="99999";_div.style.fontSize="16px";_div.innerHTML=_html;document.body.appendChild(_div)}
var __domain__="http://"+location.hostname,pageMessage={domain:__domain__,toDomain:"string"==typeof myHost?myHost.slice(0,-1):__domain__,user:{}};function $extend(a,b){for(var c in b)a[c]=b[c]}function getCookie(a){return(a=document.cookie.match(RegExp("(?:^|;)\\s*"+a+"=([^;]*)")))?decodeURIComponent(a[1]):null}
(function(){var a=getCookie("_vinfo");pageMessage.userCheck=a&&"deleted"!=a&&getCookie("ticket_v")?1:0;if(pageMessage.userCheck){pageMessage.userCheck=1;var b=getCookie("_coin6");if(b){var a=a.split("|"),c=encodeURIComponent(getCookie("ticket_v")),a=a[2],d=getCookie("_rinfo"),b=b.split(":");pageMessage.user={pic:d||"http://r.6.cn/imges/new_idx/ic_unknowMale_2.gif",encpass:c,username:a,uid:b[0],_6b:b[1],rich:b[2],star:b[3],nickname:b[4],rid:b[5],vip:b[6],fid:b[7],_6d:b[8],cloaking:parseInt(b[9]),rich_next:b[10],
star_next:b[11],frozen:1E4==b[12]||10001==b[12],from:b[13],ltime:b[14],endfollow:b[15],army:b[16]}}}if(!pageMessage.user.uid)c=(c=getCookie("_LiveGuestUser"))?c.split("|")[0]:Math.floor(1E8*Math.random()+18E8),pageMessage.user.guest_id=c})();
var _puser=pageMessage.user,Login={curHost:pageMessage.domain,$:function(a){return document.getElementById(a)},getHtml:function(){var a="",a=pageMessage.user,b=getCookie("ticket_v"),c=b&&b.slice(-5)||"",d=-1<window.location.host.indexOf("dev.")?"v.6.cn":document.domain;if(a.uid)var b='<li class="clickMore" id="cloaking"><a '+(1==a.cloaking?'class="offline" ':"online")+'title="\u5f53\u524d'+(1==a.cloaking?"\u9690\u8eab":"\u663e\u8eab")+'" href="javascript:void(0)" onmouseover="setCloaking.yvisible($(this))"><span>\u5f53\u524d'+
(a.cloaking?"\u9690\u8eab":"\u663e\u8eab")+"</span><i></i></a></li>",e='<li class="detail" style="display:none;"><a href="'+pageMessage.toDomain+'/user/detail.php" target="_blank" id="coin" title="\u67e5\u770b\u6211\u7684\u8d26\u5355"><i></i>'+a._6b+'</a></li><li class="coin6" style="display:none;"><a href="http://v.6.cn/user/exchange.php#t32_2" id="coin6" target="_blank" class="bean" title="\u5151\u6362\u516d\u5e01"><i></i>'+a._6d+'</a></li><li class="pay"><a target="_blank" href="'+pageMessage.toDomain+
'/user/payshow.php?i=1">\u5145\u503c</a></li><li class="help"><a href="http://v.6.cn/help.php" target="_blank">\u5e2e\u52a9</a></li>',c='<li class="signout"><a href="//passport.6.cn/sso/logout.php?domain='+d+"&prod="+c+"&url="+encodeURIComponent("//"+location.host+"/logout_test.php")+"&next_action="+encodeURIComponent(location.href)+'">\u79bb\u5f00</a></li>',a=window.event_page?"<ul>"+(a.frozen?'<li class="frozen"><a href="'+pageMessage.toDomain+'/user/frozen.php">\u6b64\u8d26\u53f7\u5f02\u5e38\uff0c\u67e5\u770b\u8be6\u60c5</a></li>':
'<li class="myMail"><a href="/user/secretmail/mailList.php" target="_blank" id="myMailTool"><span></span></a></li><li class="userName" onmouseover="this.className=\'menuItem userName\'" onmouseout="this.className=\'userName\'"><a href="'+pageMessage.toDomain+"/"+a.rid+'" target="_blank"><img alt="'+a.nickname+'" src="'+a.pic+'"/>'+a.nickname+'<i class="ico"></i></a><div class="menu-list">'+e.replace(/li(?=\s|>)/gi,"span")+c.replace(/li(?=\s|>)/,"span")+"</div></li>")+"</ul>":"<ul>"+(a.frozen?'<li class="frozen"><a href="'+
pageMessage.toDomain+'/user/frozen.php">\u6b64\u8d26\u53f7\u5f02\u5e38\uff0c\u67e5\u770b\u8be6\u60c5</a></li><li class="clickMore" id="myAccountTool"><a href="" class="sjx">\u7ba1\u7406\u4e2d\u5fc3</a></li>':b+'<li class="userName"><a href="'+pageMessage.toDomain+"/"+a.rid+'" target="_blank"><img alt="'+a.nickname+'" src="'+a.pic+'"></a><a href="'+pageMessage.toDomain+"/"+a.rid+'" target="_blank">'+a.nickname+"("+a.rid+')</a></li><li class="changename clickMore" onclass="changename_on" id="changename"><a href="#changename"><span>\u6362\u6635\u79f0</span><i></i></a></li><li class="myControl" onclass="myControl_on" id="myAccountTool"><a href="javascript:void(0)" class="sjx"><span>\u7ba1\u7406\u4e2d\u5fc3</span><i></i></a></li><li class="myMail"><a href="/user/secretmail/mailList.php" target="_blank" id="myMailTool"><span></span></a></li>'+
e)+c+"</ul>";else a='<ul>\t\t\t\t<li class="login"><a href="#" onclick="Login.toLogin(); return false">\u767b\u5f55</a></li>\t\t\t\t<li class="register"><a href="" onclick="Login.toLogin(1); return false">\u6ce8\u518c</a></li>\t\t\t\t<li class="help" style="background:none"><a href="http://v.6.cn/help.php" target="_blank">\u5e2e\u52a9</a></li>\t\t\t  </ul>';return a},toLogin:function(a){pageMessage.login_hidden?alert("\u60a8\u5c1a\u672a\u767b\u5f55\uff01"):loginFast.login(a)},to6:"",write:function(a){var b=
this.$("userPanel")||this.$("userPanel_index");if(b&&(this.to6="string"==typeof a?a:"http://www.6.cn",b.innerHTML=this.getHtml(),this.up_coin6(),/MSIE\s*?6\.0/.test(navigator.userAgent)&&this.$("headerBar"))){var c=this.$("headerBar").getElementsByTagName("div")[0];window.onresize=function(){c.style.width=940>document.documentElement.clientWidth?"1000px":"100%"};$LAB.script(JSF.png).wait(function(){DD_belatedPNG.fix("#headerBar img");DD_belatedPNG.fix("#headerBar div.zbName em")})}},up_coin6:function(){var a=
new Image;a.onerror=function(){var a=getCookie("_coin6");if(a){var c=a.split(":");pageMessage.user._6b=c[1];pageMessage.user._6d=c[8];var d=Login.$("coin"),a=Login.$("coin6");d.innerHTML="<i></i>"+c[1];a.innerHTML="<i></i>"+c[8];d.parentNode.style.display="";a.parentNode.style.display=""}};a.src="/api/liveInfoCk.php"},getUserInfo:function(){return{userId:_puser.uid,userName:_puser.username,pwd:_puser.encpass}}};
